import { createContext, useContext, useEffect, useState } from 'react'
import type { ReactNode } from 'react'

type Direction = 'rtl' | 'ltr'
type Language = 'ar' | 'en'

interface LanguageContextType {
    language: Language
    direction: Direction
    toggleLanguage: () => void
    t: (key: string, variables?: Record<string, string>) => string
}

const translations = {
    ar: {
        'app.title': 'سرمد',

        // Navigation
        'nav.dashboard': 'الرئيسية',
        'nav.cms': 'إدارة المحتوى',
        'nav.questions': 'التقييم والتوجيه',
        'nav.staff': 'إدارة الموظفين',
        'nav.users': 'إدارة المستخدمين',
        'nav.pricing': 'الخدمات والتسعير',
        'nav.orders': 'العمليات',
        'nav.reports': 'التحليلات والتقارير',
        'nav.integrations': 'التكاملات والإعدادات',
        'nav.audit': 'التدقيق والامتثال',
        'nav.platform_settings': 'إعدادات المنصة',
        'nav.notifications': 'الإشعارات',
        'pricing.numbered_title': '2 - إعداد التسعير والباقات',

        // User & Header
        'user.admin': 'المسؤول العام',
        'search.placeholder': 'بحث...',
        'search.placeholder_platform': 'بحث في المنصة...',
        'role.superadmin': 'المدير العام',
        'role.adminoperations': 'مدير العمليات',
        'role.adminclinical': 'مدير العيادة',
        'role.coach': 'مدرب',

        // Dashboard
        'dashboard.welcome': 'مرحباً بك يا {name}',
        'dashboard.subtitle': 'إليك ملخص أداء المنصة اليوم',
        'dashboard.overview': 'نظرة عامة على النظام',
        'dashboard.users': 'إجمالي المستخدمين',
        'dashboard.completed_tests': 'الاختبارات المكتملة (30 يوم)',
        'dashboard.upcoming_webinars': 'ويبنار قادم (هذا الشهر)',
        'dashboard.new_orders': 'طلبات جديدة',
        'dashboard.view_all': 'عرض الكل',
        'dashboard.recent_activity': 'النشاط الأخير',
        'dashboard.system_alerts': 'تنبيهات النظام',
        'dashboard.view_all_alerts': 'عرض جميع التنبيهات',

        // Content
        'content.management_title': 'إدارة المحتوى التعليمي',
        'content.management_subtitle': 'مكتبة المحتوى والمراجعة والموافقة',
        'content.stats.total': 'إجمالي المحتوى',
        'content.stats.published': 'منشور',
        'content.stats.pending': 'قيد المراجعة',
        'content.stats.drafts': 'مسودات',
        'content.explore_more': 'تصفح محتوى تعليمي إضافي',
        'content.explore.faqs': 'الأسئلة الشائعة',
        'content.explore.faqs_desc': 'تستطيع أن ترى الأسئلة الشائعة',
        'content.explore.faqs_link': 'تصفح كل الأسئلة',
        'content.explore.webinars': 'الندوات المسجلة',
        'content.explore.webinars_desc': 'تستطيع أن ترى الندوات السابقة',
        'content.explore.webinars_link': 'تصفح كل الندوات المسجلة',
        'content.explore.success_stories': 'قصص النجاح',
        'content.explore.success_stories_desc': 'تستطيع أن ترى قصص النجاح',
        'content.explore.success_stories_link': 'تصفح كل قصص النجاح',
        'content.tabs.all': 'الكل',
        'content.tabs.videos': 'فيديوهات',
        'content.tabs.articles': 'مقالات',
        'content.tabs.courses': 'كورسات',
        'content.add.selection_title': 'إضافة محتوى جديد',
        'content.add.selection_subtitle': 'اختر نوع المحتوى الذي ترغب في إنشائه وإضافته للمنصة',
        'content.add.type.article': 'مقال',
        'content.add.type.article_desc': 'كتابة المقالات التعليمية وتوعوية حول النوم وصحة الجسم بشكل احترافي',
        'content.add.type.video': 'فيديو',
        'content.add.type.video_desc': 'رفع ومشاركة مقاطع فيديو تعليمية أو إرشادية للمستخدمين والزوار',
        'content.add.type.course': 'دورة تدريبية',
        'content.add.type.course_desc': 'إنشاء دورات تعليمية شاملة، دروساً مفصلة، اختبارات وشهادات إتمام',
        'content.add.type.success_story': 'قصة نجاح',
        'content.add.type.success_story_desc': 'مشاركة تجارب واقعية ملهمة لمرضى استعادوا جودة حياتهم مع خدماتنا',
        'content.add.type.webinar': 'جدولة ندوة مباشرة',
        'content.add.type.webinar_desc': 'تنظيم لقاءات تفاعلية مباشرة عبر الإنترنت مع مختصين للنوم',
        'content.add.type.faq': 'الأسئلة الشائعة',
        'content.add.type.faq_desc': 'إضافة وإدارة الأسئلة الشائعة لتسهيل وصول المرضى للمعلومات السريعة',
        'content.add.action.article': 'أضف مقال',
        'content.add.action.video': 'رفع فيديو جديد',
        'content.add.action.course': 'رفع دورة جديدة',
        'content.add.action.success_story': 'أضف قصة جديدة',
        'content.add.action.webinar': 'جدولة موعد ندوة',
        'content.add.action.faq': 'تحديث الأسئلة',
        'content.back_to_list': 'العودة لإدارة المحتوى',
        'content.available_count': 'محتوى متاح',

        'content.library': 'مكتبة المحتوى',
        'content.new': 'محتوى جديد',
        'content.edit': 'تعديل',
        'content.delete': 'حذف',
        'content.delete_confirm_title': 'حذف المحتوى؟',
        'content.delete_confirm_desc': 'هل أنت متأكد من رغبتك في حذف هذا المحتوى نهائياً؟ لا يمكن التراجع عن هذا الإجراء.',
        'content.confirm_delete': 'نعم، قم بالحذف',
        'content.cancel': 'إلغاء',
        'content.edit_title': 'تعديل المحتوى',
        'content.add_new_title': 'إضافة محتوى جديد',
        'content.duration_label': 'المدة',
        'content.empty_library': 'مكتبة المحتوى فارغة حالياً',
        'content.start_first_article': 'ابدأ بإضافة أول محتوى',
        'content.status.published': 'منشور',
        'content.example.title': 'نصائح للنوم العميق',
        'content.example.tags': 'نصائح عامة • حمل',

        // Orders
        'orders.title': 'قائمة الطلبات',
        'orders.loading': 'جاري التحميل...',
        'orders.empty': 'لا توجد طلبات حالياً',
        'orders.empty_desc': 'سيتم ظهور طلبات Sleep Test هنا',
        'orders.count_suffix': 'طلبات',
        'orders.status.all': 'كل الحالات',
        'orders.status.requested': 'مطلوب',
        'orders.status.confirmed': 'مؤكد',
        'orders.status.shipped': 'تم الشحن',
        'orders.status.delivered': 'تم التوصيل',
        'orders.status.in_use': 'قيد الاستخدام',
        'orders.status.returned': 'تم الإرجاع',
        'orders.status.analysis': 'قيد التحليل',
        'orders.status.report_ready': 'التقرير جاهز',
        'orders.status.closed': 'مغلق',
        'orders.filter_by_status': 'تصفية حسب الحالة',
        'orders.card.id': 'رمز الطلب',
        'orders.card.customer': 'العميل',
        'orders.card.date': 'تاريخ الطلب',
        'orders.card.amount': 'قيمة الطلب',
        'orders.card.tracking': 'رقم التتبع',
        'orders.card.btn_details': 'تفاصيل كاملة',
        'orders.card.btn_track': 'تتبع الشحنة',
        'orders.card.no_tracking': 'لا يوجد رقم تتبع',

        // Users
        'users.title': 'سجل المستخدمين',
        'users.search_placeholder': 'ابحث بالاسم أو رقم الهاتف...',
        'users.view_details': 'عرض التفاصيل',
        'users.email': 'البريد الإلكتروني',
        'users.language': 'اللغة المفضلة',
        'users.segment': 'الشريحة',
        'users.consent': 'الموافقة',
        'users.consent.version': 'إصدار الموافقة',
        'users.consent.date': 'تاريخ الموافقة',
        'users.updated_at': 'آخر تحديث',
        'users.no_data': 'غير متوفر',

        // Enrollments
        'enrollments.title': 'إدارة الاشتراكات',
        'enrollments.program': 'البرنامج',
        'enrollments.start_date': 'تاريخ البدء',
        'enrollments.day_index': 'اليوم الحالي',
        'enrollments.metrics': 'المقاييس',
        'enrollments.adherence': 'الالتزام',
        'enrollments.outcome': 'النتيجة',
        'enrollments.empty': 'لا توجد اشتراكات برامج حالياً',
        'users.col.name': 'الاسم',
        'users.col.role': 'الدور',
        'users.col.date': 'تاريخ التسجيل',
        'users.col.status': 'الحالة',

        // Webinars
        'webinars.title': 'إدارة الويبنار',
        'webinars.schedule_new': ' جدولة ويبنار',
        'webinars.empty_desc': 'سيتم عرض الجلسات القادمة والمسجلة هنا',
        'webinars.count_suffix': 'ويبنار',
        'webinars.attendees_title': 'قائمة الحضور',
        'webinars.attendees_registered': 'مسجل',
        'webinars.attendees_empty': 'لا يوجد مسجلين حالياً لهذه الجلسة',
        'webinars.col_user': 'المستخدم',
        'webinars.col_phone': 'رقم الهاتف',
        'webinars.col_reg_date': 'تاريخ التسجيل',
        'webinars.col_status': 'حالة الحضور',
        'webinars.status_attended': '✅ حضر',
        'webinars.status_pending': '⌛ لم يحضر',

        // Webinar Form
        'webinars.form.thumbnail': 'الصورة التعريفية للويبنار',
        'webinars.form.upload_hint': 'انقر لرفع صورة الويبنار',
        'webinars.form.upload_size': 'ينصح بمقاس 1080×1920 بكسل',
        'webinars.form.title': 'عنوان الويبنار',
        'webinars.form.description': 'وصف الويبنار',
        'webinars.form.recording_url': 'رابط التسجيل (اختياري)',
        'webinars.form.language': 'لغة الويبنار',
        'webinars.form.target_segment': 'الفئة المستهدفة',
        'webinars.form.speaker': 'اسم المتحدث',
        'webinars.form.date_time': 'الموعد والوقت',
        'webinars.form.capacity': 'الحد الأقصى للمقاعد',
        'webinars.form.price': 'سعر التذكرة (ر.س)',
        'webinars.form.video_url': 'رابط الفيديو',
        'webinars.form.video_upload': 'رفع فيديو الويبنار',
        'webinars.form.video_hint': 'اضغط لرفع الفيديو أو أدخل الرابط بالأسفل',
        'webinars.form.update': 'تحديث الجلسة',
        'webinars.form.schedule': 'جدولة الجلسة',

        // Reports
        'reports.revenue': 'إيرادات الشهر',
        'reports.new_users': 'مستخدمين جدد',
        'reports.conversion': 'نسبة التحويل',
        'reports.chart_area': 'منطقة الرسومات البيانية التفصيلية',

        // Assessments
        'assessments.title': 'إدارة التقييم والتوجيه',
        'assessments.subtitle': 'التحكم في الأسئلة والتسجيل والتوجيه',
        'assessments.add_new_question': 'إضافة سؤال جديد',
        'assessments.add_new_assessment': 'إضافة تقييم جديد',
        'assessments.tab.overview': 'نظرة عامة',
        'assessments.tab.questions': 'إدارة الأسئلة',
        'assessments.tab.scoring': 'محرك التسجيل',
        'assessments.tab.guidance': 'قواعد التوجيه',
        'assessments.stats.active': 'التقييمات',
        'assessments.stats.questions': 'إجمالي الأسئلة',
        'assessments.stats.submissions': 'التقييمات الكلية',
        'assessments.stats.completion': 'معدل الإكمال',
        'assessments.list.last_update': 'آخر تحديث',
        'assessments.list.questions': 'عدد الأسئلة',
        'assessments.list.submissions': 'التقييمات',
        'assessments.list.completion': 'معدل الإكمال',
        'assessments.questions.bank_title': 'بنك الأسئلة',
        'assessments.questions.type_multiple': 'اختيار متعدد',
        'assessments.questions.type_yesno': 'نعم/لا',
        'assessments.questions.type_numeric': 'رقمي',
        'assessments.questions.type_rating': 'مقياس (1-10)',
        'assessments.questions.type_text': 'نص حر',
        'assessments.questions.mandatory': 'إجباري',

        // Questions/Quiz
        'questions.title': 'إدارة الأسئلة',
        'questions.subtitle': 'عرض وتعديل بنك الأسئلة الخاص بالتقييم',
        'questions.add_new': ' إضافة سؤال جديد',
        'questions.cancel': 'إلغاء الإضافة',
        'questions.tab.all': 'الكل',
        'questions.tab.archived': 'المؤرشفة',
        'questions.results_info': 'يتم عرض النتائج المحملة',
        'questions.form.title': 'بيانات السؤال الجديد',
        'questions.form.desc': 'أدخل التفاصيل أدناه للإضافة الفورية',
        // Table & Form
        'questions.col.question': 'السؤال',
        'questions.col.category': 'الفئة',
        'questions.col.answers': 'عدد الإجابات',
        'questions.col.date': 'تاريخ الإنشاء',
        'questions.col.actions': 'الإجراءات',
        'questions.empty': 'لا توجد أسئلة مضافة حتى الآن',
        'questions.form.question_label': 'السؤال',
        'questions.form.question_placeholder': 'اكتب نص السؤال...',
        'questions.form.category_label': 'الفئة (اختياري)',
        'questions.form.category_placeholder': 'مثال: نفسي، اجتماعي...',
        'questions.form.submit': 'إضافة السؤال',
        'questions.form.update': 'تحديث السؤال',
        'questions.form.submitting': 'جاري الإضافة...',
        'questions.form.updating': 'جاري التحديث...',
        'questions.category_default': 'عام',
        'questions.error': 'خطأ: ',

        // FAQs
        'faqs.title': 'الأسئلة الشائعة',
        'faqs.add_new': 'إضافة سؤال جديد',
        'faqs.count_suffix': 'أسئلة',
        'faqs.empty_desc': 'سيتم عرض الأسئلة الشائعة هنا',
        'faqs.question_en': 'السؤال (English)',
        'faqs.question_ar': 'السؤال (عربي)',
        'faqs.answer_en': 'الإجابة (English)',
        'faqs.answer_ar': 'الإجابة (عربي)',

        // Success Stories Form
        'success_stories.patient_name': 'اسم المريض',
        'success_stories.title': 'عنوان القصة',
        'success_stories.journey': 'رحلة العلاج',
        'success_stories.journey_placeholder': 'أوصف رحلة المريض منذ البداية حتى التحسن من الحالة المرضية...',
        'success_stories.media_gallery': 'معرض الوسائط',
        'success_stories.publish': 'نشر القصة',
        'success_stories.save_draft': 'حفظ كمسودة',
        'success_stories.back_to_cms': 'العودة لإدارة المحتوى',
        'success_stories.add_new': 'إضافة قصة نجاح',

        // Testimonials
        'testimonials.title': 'آراء العملاء',
        'testimonials.add_new': 'إضافة رأي جديد',
        'testimonials.count_suffix': 'آراء',
        'testimonials.empty_desc': 'سيتم عرض آراء العملاء هنا',
        'testimonials.name_en': 'الاسم (English)',
        'testimonials.name_ar': 'الاسم (عربي)',
        'testimonials.content_en': 'المحتوى (English)',
        'testimonials.content_ar': 'المحتوى (عربي)',
        'testimonials.role_en': 'الدور/المهنة (English)',
        'testimonials.role_ar': 'الدور/المهنة (عربي)',
        'testimonials.rating': 'التقييم',
        'testimonials.form.image_upload': 'رفع صورة العميل',
        'testimonials.form.image_url': 'رابط الصورة',
        'testimonials.form.image_hint': 'اضغط لرفع صورة أو أدخل الرابط بالأسفل',
        'testimonials.form.video_upload': 'رفع فيديو العميل',
        'testimonials.form.video_url': 'رابط الفيديو',
        'testimonials.form.video_hint': 'اضغط لرفع فيديو أو أدخل الرابط بالأسفل',

        // Navigation (Updated)
        'nav.faqs': 'الأسئلة الشائعة',
        'nav.testimonials': 'آراء العملاء',
        'nav.consultations': 'الاستشارات',

        // Common
        'common.loading': 'جاري التحميل...',
        'common.no_data': 'لا توجد بيانات',
        'common.currency': 'ر.س',
        'common.save': 'حفظ التغييرات',
        'common.cancel': 'إلغاء',
        'common.display_order': 'ترتيب العرض',
        'common.active': 'نشط',
        'common.inactive': 'غير نشط',

        // Staff
        'staff.title': 'إدارة الموظفين',
        'staff.create': 'إضافة موظف جديد',
        'staff.edit': 'تعديل موظف',
        'staff.delete_confirm': 'هل أنت متأكد من حذف هذا الموظف؟',
        'staff.role': 'الصلاحية',
        'staff.role.Coach': 'مدرب/أخصائي',
        'staff.role.AdminOperations': 'مسؤول (عمليات)',
        'staff.role.AdminClinical': 'مسؤول (محتوى/طبي)',
        'staff.form.name': 'الاسم',
        'staff.form.email': 'البريد الإلكتروني',
        'staff.form.password': 'كلمة المرور',
        'staff.form.role': 'الصلاحية',
        'staff.list.empty': 'لا يوجد موظفين حالياً',
        'staff.password_mismatch': 'كلمات المرور غير متطابقة',

        // Auth
        'auth.login_title': 'تسجيل الدخول',
        'auth.login_subtitle': 'أدخل بياناتك للدخول إلى لوحة التحكم',
        'auth.login_button': 'دخول',
        'auth.change_password_title': 'تغيير كلمة المرور',
        'auth.change_password_subtitle': 'يجب تغيير كلمة المرور للمتابعة',
        'auth.change_password_button': 'تغيير كلمة المرور',
        'auth.new_password': 'كلمة المرور الجديدة',
        'auth.confirm_password': 'تأكيد كلمة المرور',
        'auth.logout': 'تسجيل الخروج',
        'common.delete': 'حذف',
        'common.select': 'اختر...',

        // Profile
        'nav.profile': 'الملف الشخصي',
        'profile.title': 'ملفي الشخصي',
        'profile.subtitle': 'إدارة معلوماتك الشخصية',
        'profile.change_photo': 'اضغط لتغيير الصورة',
        'profile.name': 'الاسم الكامل',
        'profile.name_placeholder': 'أدخل اسمك',
        'profile.email': 'البريد الإلكتروني',
        'profile.mobile': 'رقم الجوال',
        'profile.city': 'المدينة',
        'profile.gender': 'النوع',
        'gender.male': 'ذكر',
        'gender.female': 'أنثى',
        'profile.age_range': 'الفئة العمرية',
        'profile.specialization': 'التخصص',
        'profile.specialization_placeholder': 'مثال: طب النوم، علم نفس سريري',
        'profile.bio': 'نبذة عني',
        'profile.bio_placeholder': 'اكتب نبذة مختصرة عن نفسك',
        'profile.update_success': 'تم تحديث الملف الشخصي بنجاح',
        'profile.update_error': 'فشل تحديث الملف الشخصي',
    },
    en: {
        'app.title': 'Sarmad',

        // Navigation
        'nav.dashboard': 'Home',
        'nav.cms': 'Content Management',
        'nav.questions': 'Assessment & Guidance',
        'nav.staff': 'Staff Management',
        'nav.users': 'User Management',
        'nav.pricing': 'Services & Pricing',
        'nav.orders': 'Operations',
        'nav.reports': 'Analytics & Reports',
        'nav.integrations': 'Integrations',
        'nav.audit': 'Audit & Compliance',
        'nav.platform_settings': 'Platform Settings',
        'nav.notifications': 'Notifications',
        'pricing.numbered_title': '2 - Configuring Pricing & Packaging',
        'nav.profile': 'Profile',

        // User & Header
        'user.admin': 'General Admin',
        'search.placeholder': 'Search...',
        'search.placeholder_platform': 'Search in platform...',
        'role.superadmin': 'Super Admin',
        'role.adminoperations': 'Operations Admin',
        'role.adminclinical': 'Clinical Admin',
        'role.coach': 'Coach',

        // Dashboard
        'dashboard.welcome': 'Welcome back, {name}',
        'dashboard.subtitle': 'Here is your platform performance summary today',
        'dashboard.overview': 'System Overview',
        'dashboard.users': 'Total Users',
        'dashboard.completed_tests': 'Completed Tests (30d)',
        'dashboard.upcoming_webinars': 'Upcoming Webinar (This Month)',
        'dashboard.new_orders': 'New Orders',
        'dashboard.view_all': 'View All',
        'dashboard.recent_activity': 'Recent Activity',
        'dashboard.system_alerts': 'System Alerts',
        'dashboard.view_all_alerts': 'View All Alerts',

        // Content
        'content.management_title': 'Educational Content Management',
        'content.management_subtitle': 'Content library, review, and approval',
        'content.stats.total': 'Total Content',
        'content.stats.published': 'Published',
        'content.stats.pending': 'Reviewing',
        'content.stats.drafts': 'Drafts',
        'content.explore_more': 'Browse additional educational content',
        'content.explore.faqs': 'FAQs',
        'content.explore.faqs_desc': 'You can see the common questions',
        'content.explore.faqs_link': 'Browse all questions',
        'content.explore.webinars': 'Recorded Webinars',
        'content.explore.webinars_desc': 'You can see previous webinars',
        'content.explore.webinars_link': 'Browse all webinars',
        'content.explore.success_stories': 'Success Stories',
        'content.explore.success_stories_desc': 'You can see all success stories',
        'content.explore.success_stories_link': 'Browse all stories',
        'content.tabs.all': 'All',
        'content.tabs.videos': 'Videos',
        'content.tabs.articles': 'Articles',
        'content.tabs.courses': 'Courses',
        'content.add.selection_title': 'Add New Content',
        'content.add.selection_subtitle': 'Choose the type of content you want to create and add to the platform',
        'content.add.type.article': 'Article',
        'content.add.type.article_desc': 'Write professional educational and awareness articles about sleep and health',
        'content.add.type.video': 'Video',
        'content.add.type.video_desc': 'Upload and share educational or instructional videos for users and visitors',
        'content.add.type.course': 'Training Course',
        'content.add.type.course_desc': 'Create comprehensive educational courses, detailed lessons, tests and certificates',
        'content.add.type.success_story': 'Success Story',
        'content.add.type.success_story_desc': 'Share inspiring real-life experiences of patients who reclaimed their life quality',
        'content.add.type.webinar': 'Live Webinar',
        'content.add.type.webinar_desc': 'Organize interactive live online meetings with sleep specialists',
        'content.add.type.faq': 'FAQs',
        'content.add.type.faq_desc': 'Add and manage FAQs to facilitate patient access to quick information',
        'content.add.action.article': 'Add Article',
        'content.add.action.video': 'Upload New Video',
        'content.add.action.course': 'Upload New Course',
        'content.add.action.success_story': 'Add New Story',
        'content.add.action.webinar': 'Schedule Webinar',
        'content.add.action.faq': 'Update Questions',
        'content.back_to_list': 'Back to Management',
        'content.available_count': 'available content',

        // Content
        'content.library': 'Content Library',
        'content.new': 'New Content',
        'content.edit': 'Edit',
        'content.delete': 'Delete',
        'content.delete_confirm_title': 'Delete Content?',
        'content.delete_confirm_desc': 'Are you sure you want to delete this content permanently? This action cannot be undone.',
        'content.confirm_delete': 'Yes, Delete',
        'content.cancel': 'Cancel',
        'content.edit_title': 'Edit Content',
        'content.add_new_title': 'Add New Content',
        'content.duration_label': 'Duration',
        'content.empty_library': 'The content library is currently empty',
        'content.start_first_article': 'Start by adding your first content',
        'content.status.published': 'Published',
        'content.example.title': 'Deep Sleep Tips',
        'content.example.tags': 'General Tips • Pregnancy',

        // Orders
        'orders.title': 'Order List',
        'orders.loading': 'Loading...',
        'orders.empty': 'No orders found',
        'orders.empty_desc': 'Sleep Test orders will appear here',
        'orders.count_suffix': 'orders',
        'orders.status.all': 'All Statuses',
        'orders.status.requested': 'Requested',
        'orders.status.confirmed': 'Confirmed',
        'orders.status.shipped': 'Shipped',
        'orders.status.delivered': 'Delivered',
        'orders.status.in_use': 'In Use',
        'orders.status.returned': 'Returned',
        'orders.status.analysis': 'Analysis',
        'orders.status.report_ready': 'Report Ready',
        'orders.status.closed': 'Closed',
        'orders.filter_by_status': 'Filter by Status',
        'orders.card.id': 'Order ID',
        'orders.card.customer': 'Customer',
        'orders.card.date': 'Order Date',
        'orders.card.amount': 'Order Amount',
        'orders.card.tracking': 'Tracking Ref',
        'orders.card.btn_details': 'Full Details',
        'orders.card.btn_track': 'Track Order',
        'orders.card.no_tracking': 'No Tracking Ref',

        // Users
        'users.title': 'User Registry',
        'users.search_placeholder': 'Search by name or phone...',
        'users.view_details': 'View Details',
        'users.email': 'Email Address',
        'users.language': 'Preferred Language',
        'users.segment': 'Segment',
        'users.consent': 'Consent',
        'users.consent.version': 'Consent Version',
        'users.consent.date': 'Consent Date',
        'users.updated_at': 'Last Updated',
        'users.no_data': 'Not available',

        // Enrollments
        'enrollments.title': 'Program Enrollments',
        'enrollments.program': 'Program Template',
        'enrollments.start_date': 'Start Date',
        'enrollments.day_index': 'Current Day',
        'enrollments.metrics': 'Metrics',
        'enrollments.adherence': 'Adherence',
        'enrollments.outcome': 'Outcome',
        'enrollments.empty': 'No program enrollments found',
        'users.col.name': 'Name',
        'users.col.role': 'Role',
        'users.col.date': 'Join Date',
        'users.col.status': 'Status',

        // Webinars
        'webinars.title': 'Webinar Management',
        'webinars.schedule_new': 'Schedule Webinar',
        'webinars.empty_desc': 'Upcoming and recorded sessions will appear here',
        'webinars.count_suffix': 'webinars',
        'webinars.attendees_title': 'Attendee List',
        'webinars.attendees_registered': 'Registered',
        'webinars.attendees_empty': 'No attendees found for this session',
        'webinars.col_user': 'User',
        'webinars.col_phone': 'Phone Number',
        'webinars.col_reg_date': 'Registration Date',
        'webinars.col_status': 'Attendance Status',
        'webinars.status_attended': '✅ Attended',
        'webinars.status_pending': '⌛ Pending',

        // Webinar Form
        'webinars.form.thumbnail': 'Webinar Thumbnail Image',
        'webinars.form.upload_hint': 'Click to upload webinar image',
        'webinars.form.upload_size': 'Recommended: 1920x1080 pixels',
        'webinars.form.title': 'Webinar Title',
        'webinars.form.description': 'Webinar Description',
        'webinars.form.recording_url': 'Recording URL (Optional)',
        'webinars.form.language': 'Webinar Language',
        'webinars.form.target_segment': 'Target Segment',
        'webinars.form.speaker': 'Speaker Name',
        'webinars.form.date_time': 'Date & Time',
        'webinars.form.capacity': 'Max Capacity',
        'webinars.form.price': 'Ticket Price (SAR)',
        'webinars.form.video_url': 'Video URL',
        'webinars.form.video_upload': 'Upload Webinar Video',
        'webinars.form.video_hint': 'Click to upload or enter URL below',
        'webinars.form.update': 'Update Session',
        'webinars.form.schedule': 'Schedule Session',

        // Reports
        'reports.revenue': 'Monthly Revenue',
        'reports.new_users': 'New Users',
        'reports.conversion': 'Conversion Rate',
        'reports.chart_area': 'Detailed Analytics Area',

        // Assessments
        'assessments.title': 'Assessment & Guidance',
        'assessments.subtitle': 'Control questions, scoring, and guidance rules',
        'assessments.add_new_question': 'Add New Question',
        'assessments.add_new_assessment': 'Add New Assessment',
        'assessments.tab.overview': 'Overview',
        'assessments.tab.questions': 'Question Management',
        'assessments.tab.scoring': 'Scoring Engine',
        'assessments.tab.guidance': 'Guidance Rules',
        'assessments.stats.active': 'Assessments',
        'assessments.stats.questions': 'Total Questions',
        'assessments.stats.submissions': 'Total Assessments',
        'assessments.stats.completion': 'Completion Rate',
        'assessments.list.last_update': 'Last Update',
        'assessments.list.questions': 'Question Count',
        'assessments.list.submissions': 'Assessments',
        'assessments.list.completion': 'Completion Rate',
        'assessments.questions.bank_title': 'Question Bank',
        'assessments.questions.type_multiple': 'Multiple Choice',
        'assessments.questions.type_yesno': 'Yes/No',
        'assessments.questions.type_numeric': 'Numeric',
        'assessments.questions.type_rating': 'Rating (1-10)',
        'assessments.questions.type_text': 'Free Text',
        'assessments.questions.mandatory': 'Mandatory',

        // Questions/Quiz
        'questions.title': 'Question Management',
        'questions.subtitle': 'View and edit the validation question bank',
        'questions.add_new': '+ Add New Question',
        'questions.cancel': 'Cancel',
        'questions.tab.all': 'All',
        'questions.tab.archived': 'Archived',
        'questions.results_info': 'Showing loaded results',
        'questions.form.title': 'New Question Data',
        'questions.form.desc': 'Enter details below to add immediately',
        // Table & Form
        'questions.col.question': 'Question',
        'questions.col.category': 'Category',
        'questions.col.answers': 'Answer Count',
        'questions.col.date': 'Created At',
        'questions.col.actions': 'Actions',
        'questions.empty': 'No questions added yet',
        'questions.form.question_label': 'Question',
        'questions.form.question_placeholder': 'Enter question text...',
        'questions.form.category_label': 'Category (Optional)',
        'questions.form.category_placeholder': 'E.g. Psychological, Social...',
        'questions.form.submit': 'Add Question',
        'questions.form.update': 'Update Question',
        'questions.form.submitting': 'Adding...',
        'questions.form.updating': 'Updating...',
        'questions.category_default': 'General',
        'questions.error': 'Error: ',

        // FAQs
        'faqs.title': 'FAQs',
        'faqs.add_new': 'Add New FAQ',
        'faqs.count_suffix': 'questions',
        'faqs.empty_desc': 'FAQs will appear here',
        'faqs.question_en': 'Question (English)',
        'faqs.question_ar': 'Question (Arabic)',
        'faqs.answer_en': 'Answer (English)',
        'faqs.answer_ar': 'Answer (Arabic)',

        // Success Stories Form
        'success_stories.patient_name': 'Patient Name',
        'success_stories.title': 'Story Title',
        'success_stories.journey': 'Treatment Journey',
        'success_stories.journey_placeholder': 'Describe the patient story from the beginning to improvement...',
        'success_stories.media_gallery': 'Media Gallery',
        'success_stories.publish': 'Publish Story',
        'success_stories.save_draft': 'Save as Draft',
        'success_stories.back_to_cms': 'Back to Content',
        'success_stories.add_new': 'Add Success Story',

        // Testimonials
        'testimonials.title': 'Testimonials',
        'testimonials.add_new': 'Add New Testimonial',
        'testimonials.count_suffix': 'testimonials',
        'testimonials.empty_desc': 'Testimonials will appear here',
        'testimonials.name_en': 'Name (English)',
        'testimonials.name_ar': 'Name (Arabic)',
        'testimonials.content_en': 'Content (English)',
        'testimonials.content_ar': 'Content (Arabic)',
        'testimonials.role_en': 'Role/Bio (English)',
        'testimonials.role_ar': 'Role/Bio (Arabic)',
        'testimonials.rating': 'Rating',
        'testimonials.form.image_upload': 'Upload Client Photo',
        'testimonials.form.image_url': 'Image URL',
        'testimonials.form.image_hint': 'Click to upload or enter URL below',
        'testimonials.form.video_upload': 'Upload Client Video',
        'testimonials.form.video_url': 'Video URL',
        'testimonials.form.video_hint': 'Click to upload or enter URL below',

        // Navigation
        'nav.faqs': 'FAQs',
        'nav.testimonials': 'Testimonials',
        'nav.consultations': 'Consultations',

        // Common
        'common.loading': 'Loading...',
        'common.no_data': 'No Data',
        'common.currency': 'SAR',
        'common.save': 'Save Changes',
        'common.cancel': 'Cancel',
        'common.display_order': 'Display Order',

        // Staff
        'staff.title': 'Staff Management',
        'staff.create': 'Add New Staff',
        'staff.edit': 'Edit Staff',
        'staff.delete_confirm': 'Are you sure you want to delete this staff member?',
        'staff.role': 'Role',
        'staff.role.Coach': 'Coach/Specialist',
        'staff.role.AdminOperations': 'Admin (Operations)',
        'staff.role.AdminClinical': 'Admin (Content/Clinical)',
        'staff.form.name': 'Name',
        'staff.form.email': 'Email',
        'staff.form.password': 'Password',
        'staff.form.role': 'Role',
        'staff.list.empty': 'No staff members found',
        'staff.password_mismatch': 'Passwords do not match',

        // Auth
        'auth.login_title': 'Login',
        'auth.login_subtitle': 'Enter your credentials to access the dashboard',
        'auth.login_button': 'Sign In',
        'auth.change_password_title': 'Change Password',
        'auth.change_password_subtitle': 'You must change your password to continue',
        'auth.change_password_button': 'Change Password',
        'auth.new_password': 'New Password',
        'auth.confirm_password': 'Confirm Password',
        'auth.logout': 'Logout',
        'common.delete': 'Delete',
        'common.select': 'Select...',
        'common.active': 'Active',
        'common.inactive': 'Inactive',

        // Profile
        'profile.title': 'My Profile',
        'profile.subtitle': 'Manage your personal information',
        'profile.change_photo': 'Click to change photo',
        'profile.name': 'Full Name',
        'profile.name_placeholder': 'Enter your name',
        'profile.email': 'Email Address',
        'profile.mobile': 'Mobile Number',
        'profile.city': 'City',
        'profile.gender': 'Gender',
        'gender.male': 'Male',
        'gender.female': 'Female',
        'profile.age_range': 'Age Range',
        'profile.specialization': 'Specialization',
        'profile.specialization_placeholder': 'E.g. Sleep Medicine, Clinical Psychology',
        'profile.bio': 'Bio',
        'profile.bio_placeholder': 'Write a brief biography',
        'profile.update_success': 'Profile updated successfully',
        'profile.update_error': 'Failed to update profile',
    }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>('ar')
    const direction = language === 'ar' ? 'rtl' : 'ltr'

    useEffect(() => {
        document.documentElement.dir = direction
        document.documentElement.lang = language
    }, [direction, language])

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'ar' ? 'en' : 'ar')
    }

    const t = (key: string, variables?: Record<string, string>) => {
        const langData = (translations as any)[language]
        let text = langData[key] || key

        if (variables) {
            Object.entries(variables).forEach(([vKey, vValue]) => {
                text = text.replace(new RegExp(`{${vKey}}`, 'g'), vValue)
            })
        }

        return text
    }

    return (
        <LanguageContext.Provider value={{ language, direction, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
    const context = useContext(LanguageContext)
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider')
    }
    return context
}
